<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Serialization/embedded-recipe.json" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Loom\Loom.csproj" />
    <ProjectReference Include="..\..\src\Loom.Serialization.Json\Loom.Serialization.Json.csproj" />
    <ProjectReference Include="..\..\src\Loom.Sources.Embedded\Loom.Sources.Embedded.csproj" />
    <ProjectReference Include="..\..\src\Loom.Sources.FileSystem\Loom.Sources.FileSystem.csproj" />
    <ProjectReference Include="..\..\src\Loom.Sources.InMemory\Loom.Sources.InMemory.csproj" />
  </ItemGroup>

</Project>
